AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Authentication Service

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: B
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  VerificationCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VerificationCodes
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: N
        - AttributeName: expires
          AttributeType: N
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Roles
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: B
        - AttributeName: id
          AttributeType: B
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  InterphlixAuthenticationApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Interphlix-Authentication
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Interphlix Authentication API
          version: '1.0'
        paths:
          /signup:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /login:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /details:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: GET
                type: aws_proxy
          /verify-email:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /roles:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: GET
                type: aws_proxy
          /forgot-password:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /redicted:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InterphlixAuthenticationFunction.Arn}/invocations
                httpMethod: GET
                type: aws_proxy

  InterphlixAuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: interphlix-authentication
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: Users
        - DynamoDBCrudPolicy:
            TableName: VerificationCodes
        - DynamoDBCrudPolicy:
            TableName: Roles
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref InterphlixAuthenticationApi
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${InterphlixAuthenticationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
