name: CI/CD Pipeline

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Run tests
      run: |
        cargo test


    - name: Install Zig toolchain
      run: |
        sudo snap install zig --beta --classic

    - name: Cache Zig toolchain
      uses: actions/cache@v3
      with:
        path: /snap/zig
        key: ${{ runner.os }}-zig

    - name: Install snapd
      run: |
        sudo apt-get update
        sudo apt-get install -y snapd
      
    - name: Cache snapd
      uses: actions/cache@v3
      with:
        path: /var/lib/snapd
        key: ${{ runner.os }}-snapd

    - name: Install Zig toolchain
      run: |
        sudo snap install zig --beta --classic

    - name: Install Cargo Lambda
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: cargo-lambda/cargo-lambda

    - name: Ensure target directory exists
      run: |
        mkdir -p target/lambda/authentication

    - name: compile the code
      run: |
        cargo lambda build --output-format zip

    - name: Verify build output
      run: |
        ls -R target/lambda/authentication
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lambda-artifacts
        path: target/lambda/authentication

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: lambda-artifacts

    - name: Package SAM application
      run: |
        ls -a
#        sam package --template-file template.yaml --s3-bucket interphlix-auth-code --output-template-file packaged.yaml --region us-east-1

    # - name: Deploy SAM application
    #   run: |
    #     sam deploy --template-file packaged.yaml --stack-name interphlix-authentication --capabilities CAPABILITY_IAM --region us-east-1
